title: Карманный акселератор
description: Walking Startup помогает запустить ИТ-бизнес быстро, без кода и вложений.
url: https://walkingstartup.ru
disqus_shortname: walkingstartup

logo: https://walkingstartup.ru/img/walking-startup-logo.png
twitter:
  username: walkingstartup

facebook:
  publisher: walkingstartup

social:
  links: 

google_site_verification: googled1b52caafecee6fd.html
company:
  founded: ноябрь 2017
  team_size: 1
  address: 450001, Пр. Октября,2 (Уфа, Росссия)
  
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

paginate: 10
paginate_path: "blog/:num/"
blog_name: 
blog_description: 
permalink: pretty
timezone: Asia/Yekaterinburg

collections:
  gallery:
    name: Gallery
    output: false
  experts:
    name: Партнеры
    output: false
  staff:
    name: Команда
    _hide_content: true
    output: false
  authors:
    name: Авторы
    output: false
  customers:
    name: Проекты
    output: true
    permalink: /projects/:name/
defaults:
  - scope:
      path: ""
      type: "customers"
    values:
      layout: "customer"
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post

development:
  google_analytics_key: "UA-108068030-1"
  google_maps_embed_api_key: 
  keen:
    project_id: 
    write_key:

staging:
  google_analytics_key: "UA-108068030-1"
  google_maps_embed_api_key: 
  keen:
    project_id: 
    write_key: 

production:
  google_analytics_key: "UA-108068030-1"
  google_maps_embed_api_key: 
  keen:
    project_id: 
    write_key: 
